'use strict';
/**
 * Light Recorder - main process.
 *
 * Orchestrates windows, hotkeys and the recording engine. Deliberately does
 * no media work itself: video goes GPU -> ffmpeg -> disk, and audio is mixed
 * in a hidden renderer then piped straight out. This process only ever moves
 * small control messages around, which is why memory stays flat during a
 * multi-hour recording.
 */
const {
  app, BrowserWindow, ipcMain, screen, shell,
  dialog, Tray, Menu, nativeImage, session, desktopCapturer
} = require('electron');
const path = require('path');
const fs = require('fs');
const net = require('net');
const { execFile, spawn } = require('child_process');

const settings = require('./settings');
const encoders = require('./encoders');
const sources = require('./sources');
const { Recorder, remux } = require('./recorder');
const { TabRecorder } = require('./tabRecorder');
const { Bridge } = require('./bridge');
const { AudioSessions } = require('./audioSessions');

// Chromium flags: we render a handful of tiny always-on-top panels, so the
// GPU niceties cost more than they buy. Keeps idle footprint down.
app.commandLine.appendSwitch('disable-renderer-backgrounding');
app.commandLine.appendSwitch('disable-features', 'CalculateNativeWinOcclusion');
app.disableHardwareAcceleration();

const RENDERER = path.join(__dirname, '..', 'renderer');
const PRELOAD = path.join(__dirname, '..', 'preload', 'api.js');
const ASSETS = path.join(__dirname, '..', '..', 'assets');

/** Commands arrive here from the resident hotkey listener. */
const PIPE = '\\\\.\\pipe\\light-recorder-cmd';

// The overlay collapses to just a timer, a stop button and an expand chevron
// while recording, so it stays out of the way. It is anchored by its right
// edge, so shrinking pulls the left side in rather than moving the whole pill.
const OVERLAY_H = 54;
const OVERLAY_FULL_W = 412;
const OVERLAY_COMPACT_W = 196;

/** @type {Record<string, BrowserWindow|null>} */
const win = { overlay: null, picker: null, settings: null, mixer: null, audio: null };

let tray = null;
let encoderInfo = { ffmpeg: null, available: [], best: null, hasDdagrab: false };
let currentSource = null;
let recorder = new Recorder();
let tabRecorder = new TabRecorder();
let bridge = null;
let audioSessions = new AudioSessions();
let activeMode = null;            // 'native' | 'tab'
let lastStatus = {};
let overlayCompact = false;
let repositioningOverlay = false; // suppresses the 'moved' handler during setBounds

// ---------------------------------------------------------------- utilities

function broadcast(channel, payload) {
  for (const key of Object.keys(win)) {
    const w = win[key];
    if (w && !w.isDestroyed() && w.webContents && !w.webContents.isDestroyed()) {
      w.webContents.send(channel, payload);
    }
  }
}

function toast(message, kind = 'info') {
  broadcast('toast', { message, kind });
}

function isRecording() {
  return recorder.isRecording || tabRecorder.isRecording;
}

function pushState() {
  const s = settings.all();
  const active = activeMode === 'tab' ? tabRecorder.status() : recorder.status();
  lastStatus = {
    recording: isRecording(),
    state: active.state,
    mode: activeMode,
    file: active.file,
    startedAt: active.startedAt,
    elapsedMs: active.elapsedMs,
    progress: active.progress,
    source: currentSource,
    compact: overlayCompact,
    settings: s,
    encoders: {
      available: encoderInfo.available,
      best: encoderInfo.best,
      ffmpeg: encoderInfo.ffmpeg,
      hasDdagrab: encoderInfo.hasDdagrab
    },
    bridge: {
      connected: bridge ? bridge.connected : false,
      port: s.bridgePort,
      token: bridge ? bridge.token : '',
      tabs: bridge ? bridge.tabs : []
    }
  };
  broadcast('state', lastStatus);
  return lastStatus;
}

/** Tray icon. Generated by `npm run icons`; see assets/build-icons.js. */
function trayImage(recording) {
  const file = path.join(ASSETS, recording ? 'tray-rec.png' : 'tray-idle.png');
  const img = nativeImage.createFromPath(file);
  return img.isEmpty() ? nativeImage.createEmpty() : img;
}

function appIcon() {
  const ico = path.join(ASSETS, 'icon.ico');
  const img = nativeImage.createFromPath(ico);
  return img.isEmpty() ? undefined : img;
}

// ------------------------------------------------------------------ windows

/**
 * Keep our own UI out of the recording (WDA_EXCLUDEFROMCAPTURE), so the
 * overlay never has to hide itself while recording.
 *
 * Timing matters: setting this before the window is shown silently does
 * nothing on Windows. Verified against a real ddagrab capture - windows
 * protected pre-show still appeared in the frame, post-show ones did not.
 * It is therefore applied on every show, not once at construction.
 */
function protectFromCapture(w) {
  const apply = () => { try { w.setContentProtection(true); } catch (_) {} };
  if (w.isVisible()) apply();
  w.on('show', apply);
  w.on('ready-to-show', () => setImmediate(apply));
}

function overlayPosition(width, height) {
  const s = settings.all();
  if (s.overlayCustomPos) {
    // Clamp into whatever display currently exists - monitors get unplugged.
    const d = screen.getDisplayNearestPoint(s.overlayCustomPos);
    const wa = d.workArea;
    return {
      x: Math.round(Math.min(Math.max(s.overlayCustomPos.x, wa.x), wa.x + wa.width - width)),
      y: Math.round(Math.min(Math.max(s.overlayCustomPos.y, wa.y), wa.y + wa.height - height))
    };
  }
  const wa = screen.getPrimaryDisplay().workArea;
  const off = s.overlayOffset || { x: 16, y: 16 };
  return { x: Math.round(wa.x + wa.width - width - off.x), y: Math.round(wa.y + off.y) };
}

function overlayWidth() {
  return overlayCompact ? OVERLAY_COMPACT_W : OVERLAY_FULL_W;
}

/**
 * Resize/reposition the overlay for the current mode, keeping the right edge
 * where it was. Stored positions always describe the full-width pill so the
 * two modes cannot drift apart.
 */
function applyOverlayLayout() {
  const w = win.overlay;
  if (!w || w.isDestroyed()) return;

  const width = overlayWidth();
  const pos = overlayPosition(OVERLAY_FULL_W, OVERLAY_H);
  repositioningOverlay = true;
  w.setBounds({
    x: pos.x + (OVERLAY_FULL_W - width),
    y: pos.y,
    width,
    height: OVERLAY_H
  });
  setImmediate(() => { repositioningOverlay = false; });
  positionMixer();
}

function setOverlayCompact(next) {
  const v = !!next;
  if (overlayCompact === v) return;
  overlayCompact = v;
  applyOverlayLayout();
  pushState();
}

function createOverlay() {
  if (win.overlay && !win.overlay.isDestroyed()) return win.overlay;

  const width = overlayWidth(), height = OVERLAY_H;
  const pos = overlayPosition(OVERLAY_FULL_W, height);
  pos.x += OVERLAY_FULL_W - width;

  const w = new BrowserWindow({
    width, height, x: pos.x, y: pos.y,
    frame: false,
    transparent: true,
    resizable: false,
    movable: true,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    show: false,
    hasShadow: false,
    backgroundColor: '#00000000',
    webPreferences: {
      preload: PRELOAD,
      contextIsolation: true,
      nodeIntegration: false,
      backgroundThrottling: false,
      spellcheck: false
    }
  });

  // Float above fullscreen games and other topmost windows.
  w.setAlwaysOnTop(true, 'screen-saver');
  w.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  protectFromCapture(w);

  w.loadFile(path.join(RENDERER, 'overlay.html'));
  w.once('ready-to-show', () => { w.show(); pushState(); });

  w.on('moved', () => {
    if (repositioningOverlay) return;      // our own setBounds, not the user
    const [x, y] = w.getPosition();
    // Normalise back to where the full-width pill would sit.
    settings.set({ overlayCustomPos: { x: x - (OVERLAY_FULL_W - overlayWidth()), y } });
    positionMixer();
  });

  w.on('closed', () => { win.overlay = null; });
  win.overlay = w;
  return w;
}

function toggleOverlay() {
  const w = createOverlay();
  if (w.isVisible()) {
    // Never let the panel vanish mid-recording without the user knowing.
    if (isRecording()) { w.focus(); return; }
    w.hide();
    closeWindow('mixer');
    maybeQuit();
  } else {
    cancelExit();
    w.showInactive();
    w.setAlwaysOnTop(true, 'screen-saver');
  }
}

function createChild(key, file, opts) {
  if (win[key] && !win[key].isDestroyed()) {
    win[key].show();
    win[key].focus();
    return win[key];
  }
  const w = new BrowserWindow(Object.assign({
    frame: false,
    transparent: false,
    backgroundColor: '#14161a',
    icon: appIcon(),
    show: false,
    skipTaskbar: true,
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    webPreferences: {
      preload: PRELOAD,
      contextIsolation: true,
      nodeIntegration: false,
      spellcheck: false
    }
  }, opts));

  protectFromCapture(w);                 // keep dialogs out of the capture too
  w.loadFile(path.join(RENDERER, file));
  w.once('ready-to-show', () => { w.show(); w.focus(); pushState(); });
  w.on('closed', () => { win[key] = null; });
  win[key] = w;
  return w;
}

function closeWindow(key) {
  const w = win[key];
  if (w && !w.isDestroyed()) w.close();
  win[key] = null;
}

function openPicker() {
  const display = screen.getDisplayNearestPoint(screen.getCursorScreenPoint());
  const width = Math.min(1000, Math.round(display.workArea.width * 0.8));
  const height = Math.min(660, Math.round(display.workArea.height * 0.8));
  // Explicitly centred on the active monitor - the requirement is that the
  // source chooser appears in the middle of the screen.
  const w = createChild('picker', 'picker.html', {
    width, height,
    x: Math.round(display.workArea.x + (display.workArea.width - width) / 2),
    y: Math.round(display.workArea.y + (display.workArea.height - height) / 2),
    alwaysOnTop: true,
    resizable: true
  });
  w.setAlwaysOnTop(true, 'screen-saver');
  return w;
}

function openSettings() {
  const display = screen.getDisplayNearestPoint(screen.getCursorScreenPoint());
  const width = 640, height = Math.min(720, Math.round(display.workArea.height * 0.9));
  return createChild('settings', 'settings.html', {
    width, height,
    x: Math.round(display.workArea.x + (display.workArea.width - width) / 2),
    y: Math.round(display.workArea.y + (display.workArea.height - height) / 2),
    alwaysOnTop: true
  });
}

function positionMixer() {
  if (!win.mixer || win.mixer.isDestroyed() || !win.overlay || win.overlay.isDestroyed()) return;
  const o = win.overlay.getBounds();
  const m = win.mixer.getBounds();
  const wa = screen.getDisplayNearestPoint({ x: o.x, y: o.y }).workArea;
  const x = Math.min(Math.max(o.x + o.width - m.width, wa.x), wa.x + wa.width - m.width);
  const y = Math.min(o.y + o.height + 8, wa.y + wa.height - m.height);
  win.mixer.setPosition(Math.round(x), Math.round(y));
}

function openMixer() {
  if (win.mixer && !win.mixer.isDestroyed()) { closeWindow('mixer'); return null; }
  const w = createChild('mixer', 'mixer.html', {
    width: 340, height: 420,
    alwaysOnTop: true,
    transparent: true,
    backgroundColor: '#00000000',
    hasShadow: false
  });
  w.setAlwaysOnTop(true, 'screen-saver');
  w.once('ready-to-show', positionMixer);
  return w;
}

/**
 * Hidden renderer that owns the audio graph: system loopback + microphone,
 * each with its own gain, mixed to 48k stereo and emitted as s16le PCM.
 * Created only while recording, so idle cost is zero.
 */
function createAudioWindow() {
  if (win.audio && !win.audio.isDestroyed()) return win.audio;
  const w = new BrowserWindow({
    width: 200, height: 120,
    show: false,
    skipTaskbar: true,
    webPreferences: {
      preload: PRELOAD,
      contextIsolation: true,
      nodeIntegration: false,
      backgroundThrottling: false,
      spellcheck: false
    }
  });
  w.loadFile(path.join(RENDERER, 'audio.html'));
  w.on('closed', () => { win.audio = null; });
  win.audio = w;
  return w;
}

function destroyAudioWindow() {
  if (win.audio && !win.audio.isDestroyed()) win.audio.destroy();
  win.audio = null;
}

// ------------------------------------------------------------------ hotkeys

/**
 * Hotkeys are owned entirely by the resident listener, never by this process.
 *
 * Two reasons. RegisterHotKey is exclusive, so both registering the same combo
 * would just conflict. More importantly, the listener is a 116 KB native
 * process that costs a few megabytes; keeping Electron alive purely to watch
 * for a keypress would cost two hundred. We write the bindings to a config
 * file the listener watches, and it re-registers them on the fly.
 */
function writeListenerConfig() {
  const hk = settings.get('hotkeys') || {};

  // How the listener should start us when we are not running. In development
  // that is electron.exe plus the project path; packaged it is our own exe.
  const exec = process.execPath;
  const execArgs = app.isPackaged ? '' : `"${app.getAppPath()}"`;

  const lines = [
    '# Written by Light Recorder. Edit hotkeys in the app, not here.',
    `exec=${exec}`,
    `args=${execArgs}`,
    `cwd=${app.getAppPath()}`,
    ''
  ];
  for (const [name, accel] of Object.entries(hk)) {
    if (accel) lines.push(`${name}=${accel}`);
  }

  try {
    fs.writeFileSync(path.join(app.getPath('userData'), 'listener.conf'), lines.join('\n'), 'utf8');
  } catch (err) {
    console.error('[listener] could not write config:', err.message);
  }
}

/** Act on a command name, whether it came from the pipe or from argv. */
function runCommand(name) {
  switch (name) {
    case 'launch':
    case 'toggleOverlay':
      toggleOverlay();
      break;

    case 'show':
      createOverlay().showInactive();
      cancelExit();
      break;

    case 'startStop':
      if (isRecording()) stopRecording();
      else { createOverlay().showInactive(); cancelExit(); startRecording(); }
      break;

    case 'record':
      if (!isRecording()) { createOverlay().showInactive(); cancelExit(); startRecording(); }
      break;

    case 'stop':
      if (isRecording()) stopRecording();
      break;

    case 'toggleMic': {
      const muted = !settings.get('micMuted');
      settings.set({ micMuted: muted });
      if (win.audio && !win.audio.isDestroyed()) win.audio.webContents.send('audio:config', settings.all());
      toast(muted ? 'Microphone muted' : 'Microphone live', 'info');
      pushState();
      break;
    }

    case 'picker':
      createOverlay().showInactive();
      cancelExit();
      openPicker();
      break;

    // Collapse/expand the pill. Not bound by default, but available to bind
    // like any other command.
    case 'toggleCompact':
      if (isRecording()) setOverlayCompact(!overlayCompact);
      break;

    case 'ping':
      break;                       // the listener only needs the connection to succeed

    case 'quit':
      app.quit();
      break;
  }
}

/**
 * Command pipe. Its existence is also how the listener knows we are running:
 * if connecting fails, it launches us instead of forwarding.
 */
function startCommandServer() {
  const server = net.createServer(sock => {
    sock.setEncoding('utf8');
    let buf = '';
    sock.on('data', d => {
      buf += d;
      let i;
      while ((i = buf.indexOf('\n')) >= 0) {
        const cmd = buf.slice(0, i).trim();
        buf = buf.slice(i + 1);
        if (cmd) runCommand(cmd);
      }
    });
    sock.on('error', () => { /* listener disconnects immediately after writing */ });
  });

  server.on('error', err => {
    console.error('[pipe] listen failed:', err.message);
  });

  try { server.listen(PIPE); } catch (err) { console.error('[pipe]', err.message); }
  return server;
}

// ------------------------------------------------------------ exit on idle

let exitTimer = null;
let hideTimer = null;

function cancelExit() {
  clearTimeout(exitTimer); exitTimer = null;
  clearTimeout(hideTimer); hideTimer = null;
}

function anyWindowOpen() {
  for (const key of ['picker', 'settings', 'mixer']) {
    const w = win[key];
    if (w && !w.isDestroyed() && w.isVisible()) return true;
  }
  return false;
}

/**
 * Quit once we are genuinely idle: nothing recording, overlay dismissed, no
 * dialogs open. The listener stays behind to catch the next hotkey, so the
 * user loses nothing by us going away.
 */
function maybeQuit() {
  if (!settings.get('exitWhenHidden')) return;
  if (isRecording()) return;
  if (anyWindowOpen()) return;
  if (win.overlay && !win.overlay.isDestroyed() && win.overlay.isVisible()) return;

  clearTimeout(exitTimer);
  // A short grace period so a hide-then-immediately-show does not kill us
  // mid-flight.
  exitTimer = setTimeout(() => {
    if (isRecording() || anyWindowOpen()) return;
    if (win.overlay && !win.overlay.isDestroyed() && win.overlay.isVisible()) return;
    app.quit();
  }, 1200);
}

/** After a recording finishes, put the overlay away by itself. */
function scheduleAutoHide() {
  const secs = Number(settings.get('autoHideAfterStopSeconds'));
  if (!secs || secs <= 0) return;
  clearTimeout(hideTimer);
  hideTimer = setTimeout(() => {
    if (isRecording()) return;
    if (win.overlay && !win.overlay.isDestroyed()) win.overlay.hide();
    closeWindow('mixer');
    maybeQuit();
  }, secs * 1000);
}

// ---------------------------------------------------------------- recording

async function startRecording() {
  if (isRecording()) return { ok: false, error: 'Already recording' };

  const s = settings.all();
  const src = currentSource || sources.defaultSource();
  currentSource = src;

  try {
    fs.mkdirSync(s.outputDir, { recursive: true });
    fs.accessSync(s.outputDir, fs.constants.W_OK);
  } catch (err) {
    const msg = `Cannot write to ${s.outputDir}. Pick another folder in Settings.`;
    toast(msg, 'error');
    return { ok: false, error: msg };
  }

  // ---- tab capture goes through the extension -----------------------------
  if (src.kind === 'tab') {
    if (!bridge || !bridge.connected) {
      const msg = 'Browser extension is not connected, so that tab cannot be recorded.';
      toast(msg, 'error');
      return { ok: false, error: msg };
    }
    activeMode = 'tab';
    try {
      tabRecorder.start({ settings: s, container: 'mp4' });
    } catch (err) {
      activeMode = null;
      return { ok: false, error: err.message };
    }
    // Recording one tab means only that tab's audio is captured, so tab B is
    // silent in the file without us muting anything the user can hear.
    bridge.startTabCapture(src.tabId, {
      fps: s.fps,
      resolution: s.resolution,
      bitrateMbps: s.bitrateMbps,
      micEnabled: s.micEnabled && !s.micMuted,
      tabAudioEnabled: s.systemAudioEnabled && !s.systemAudioMuted
    });
    setOverlayCompact(true);
    pushState();
    return { ok: true, mode: 'tab' };
  }

  // ---- screen / window capture goes through ffmpeg ------------------------
  if (!encoderInfo.ffmpeg) {
    const msg = 'ffmpeg was not found. Set its path in Settings.';
    toast(msg, 'error');
    return { ok: false, error: msg };
  }
  const encoder = encoders.pick(s.encoder, encoderInfo);
  if (!encoder) {
    const msg = 'No usable video encoder was found.';
    toast(msg, 'error');
    return { ok: false, error: msg };
  }

  const wantAudio = (s.systemAudioEnabled && !s.systemAudioMuted) || (s.micEnabled && !s.micMuted);
  activeMode = 'native';

  if (wantAudio) {
    try {
      await startAudioEngine();
    } catch (err) {
      toast(`Audio unavailable (${err.message}); recording video only.`, 'warn');
    }
  }

  try {
    await recorder.start({
      source: src,
      settings: s,
      encoder,
      ffmpeg: encoderInfo.ffmpeg,
      hasDdagrab: encoderInfo.hasDdagrab,
      wantAudio: wantAudio && !!win.audio
    });
  } catch (err) {
    activeMode = null;
    destroyAudioWindow();
    toast(`Could not start: ${err.message}`, 'error');
    return { ok: false, error: err.message };
  }

  if (tray) tray.setImage(trayImage(true));
  // Shrink to the essentials now that recording is under way.
  setOverlayCompact(true);
  pushState();
  return { ok: true, mode: 'native' };
}

function startAudioEngine() {
  return new Promise((resolve, reject) => {
    const w = createAudioWindow();
    const timer = setTimeout(() => reject(new Error('audio engine timed out')), 8000);

    const onReady = (_e, payload) => {
      if (payload && payload.ok) { clearTimeout(timer); ipcMain.off('audio:ready', onReady); resolve(payload); }
      else if (payload) { clearTimeout(timer); ipcMain.off('audio:ready', onReady); reject(new Error(payload.error || 'audio failed')); }
    };
    ipcMain.on('audio:ready', onReady);

    w.webContents.once('did-finish-load', () => {
      w.webContents.send('audio:start', settings.all());
    });
    if (!w.webContents.isLoading()) w.webContents.send('audio:start', settings.all());
  });
}

async function stopRecording() {
  if (!isRecording()) return { ok: false, error: 'Not recording' };

  const s = settings.all();
  let result;

  if (activeMode === 'tab') {
    if (bridge) bridge.stopTabCapture();
    // Give the extension a moment to flush its final MediaRecorder chunk.
    await new Promise(r => setTimeout(r, 400));
    result = await tabRecorder.stop();
  } else {
    result = await recorder.stop();
    destroyAudioWindow();
  }

  activeMode = null;
  if (tray) tray.setImage(trayImage(false));
  setOverlayCompact(false);      // back to the full pill once idle

  // Put the user's audio back exactly how it was before we started.
  try { await audioSessions.restoreAll(); } catch (_) {}
  if (bridge) bridge.restoreTabMutes();

  if (result && result.error) {
    toast(`Recording problem: ${String(result.error).split('\n').pop()}`, 'error');
  } else if (result && result.file) {
    if (s.remuxOnStop && encoderInfo.ffmpeg && /\.mp4$/i.test(result.file)) {
      toast('Finalising file…', 'info');
      const r = await remux(encoderInfo.ffmpeg, result.file);
      if (!r.ok) toast(`Saved, but could not finalise: ${r.error}`, 'warn');
    }
    let size = 0;
    try { size = fs.statSync(result.file).size; } catch (_) {}
    broadcast('saved', { file: result.file, bytes: size, durationMs: result.durationMs });
    toast(`Saved ${path.basename(result.file)}`, 'success');
  }

  pushState();
  // Done recording: put the overlay away and let the process go, leaving only
  // the tiny listener behind.
  scheduleAutoHide();
  return { ok: true, file: result && result.file };
}

// ---------------------------------------------------------------- IPC wiring

function wireIpc() {
  ipcMain.handle('app:getState', () => pushState());

  ipcMain.handle('settings:get', () => settings.all());
  ipcMain.handle('settings:set', (_e, patch) => {
    const before = settings.all();
    const after = settings.set(patch || {});
    if (patch && patch.hotkeys) writeListenerConfig();
    if (patch && patch.bridgePort && patch.bridgePort !== before.bridgePort && bridge) {
      bridge.start(after.bridgePort);
    }
    // Live audio changes take effect mid-recording.
    if (win.audio && !win.audio.isDestroyed()) win.audio.webContents.send('audio:config', after);
    pushState();
    return after;
  });
  ipcMain.handle('settings:reset', () => { const s = settings.reset(); writeListenerConfig(); pushState(); return s; });

  ipcMain.handle('settings:chooseFolder', async () => {
    const res = await dialog.showOpenDialog(win.settings || win.overlay, {
      title: 'Where should recordings be saved?',
      defaultPath: settings.get('outputDir'),
      properties: ['openDirectory', 'createDirectory']
    });
    if (res.canceled || !res.filePaths.length) return null;
    settings.set({ outputDir: res.filePaths[0] });
    pushState();
    return res.filePaths[0];
  });

  ipcMain.handle('settings:chooseFfmpeg', async () => {
    const res = await dialog.showOpenDialog(win.settings || win.overlay, {
      title: 'Locate ffmpeg.exe',
      properties: ['openFile'],
      filters: [{ name: 'ffmpeg', extensions: ['exe'] }]
    });
    if (res.canceled || !res.filePaths.length) return null;
    settings.set({ ffmpegPath: res.filePaths[0] });
    encoderInfo = await encoders.detect(res.filePaths[0], { force: true });
    pushState();
    return res.filePaths[0];
  });

  ipcMain.handle('encoders:redetect', async () => {
    encoderInfo = await encoders.detect(settings.get('ffmpegPath'), { force: true });
    pushState();
    return encoderInfo;
  });

  // ---- sources ----
  ipcMain.handle('source:list', async () => {
    const list = await sources.list({ thumbnails: true });
    const tabs = bridge && bridge.connected ? bridge.tabs : [];
    if (bridge && bridge.connected) bridge.refreshTabs();
    return { screens: list.screens, windows: list.windows, tabs, bridgeConnected: !!(bridge && bridge.connected) };
  });

  ipcMain.handle('source:select', (_e, src) => {
    currentSource = src;
    pushState();
    return currentSource;
  });

  ipcMain.handle('source:default', () => {
    currentSource = sources.defaultSource();
    pushState();
    return currentSource;
  });

  // ---- recording ----
  ipcMain.handle('rec:start', () => startRecording());
  ipcMain.handle('rec:stop', () => stopRecording());
  ipcMain.handle('rec:toggle', () => (isRecording() ? stopRecording() : startRecording()));

  // ---- audio ----
  ipcMain.on('audio:pcm', (_e, buf) => recorder.writeAudio(buf));
  ipcMain.on('audio:ready', () => { /* consumed by startAudioEngine */ });
  ipcMain.on('audio:error', (_e, msg) => toast(`Audio: ${msg}`, 'warn'));

  ipcMain.handle('audio:toggleMic', () => {
    const micMuted = !settings.get('micMuted');
    settings.set({ micMuted });
    if (win.audio && !win.audio.isDestroyed()) win.audio.webContents.send('audio:config', settings.all());
    pushState();
    return micMuted;
  });

  ipcMain.handle('audio:toggleSystem', () => {
    const systemAudioMuted = !settings.get('systemAudioMuted');
    settings.set({ systemAudioMuted });
    if (win.audio && !win.audio.isDestroyed()) win.audio.webContents.send('audio:config', settings.all());
    pushState();
    return systemAudioMuted;
  });

  ipcMain.handle('audio:listDevices', async () => {
    // Enumerated in the audio renderer, which has media permissions.
    return new Promise(resolve => {
      const w = createAudioWindow();
      const done = (_e, devices) => { ipcMain.off('audio:devices', done); resolve(devices || []); };
      ipcMain.on('audio:devices', done);
      const ask = () => w.webContents.send('audio:enumerate');
      if (w.webContents.isLoading()) w.webContents.once('did-finish-load', ask); else ask();
      setTimeout(() => { ipcMain.off('audio:devices', done); resolve([]); }, 5000);
    });
  });

  ipcMain.handle('mixer:list', async () => {
    const apps = await audioSessions.list();
    const tabs = bridge && bridge.connected ? bridge.tabs : [];
    if (bridge && bridge.connected) bridge.refreshTabs();
    return {
      apps: apps.sessions || [],
      appsError: apps.ok ? null : apps.error,
      tabs,
      bridgeConnected: !!(bridge && bridge.connected)
    };
  });

  ipcMain.handle('mixer:setAppMuted', async (_e, { pid, muted }) => {
    const r = await audioSessions.setMuted(pid, muted);
    return r;
  });

  ipcMain.handle('mixer:setTabMuted', (_e, { tabId, muted }) => {
    if (!bridge || !bridge.connected) return { ok: false, error: 'extension not connected' };
    bridge.setTabMuted(tabId, muted);
    pushState();
    return { ok: true };
  });

  // ---- windows / shell ----
  ipcMain.handle('ui:openPicker', () => { openPicker(); });
  ipcMain.handle('ui:openSettings', () => { openSettings(); });
  ipcMain.handle('ui:openMixer', () => { openMixer(); });
  ipcMain.handle('ui:toggleCompact', () => { setOverlayCompact(!overlayCompact); return overlayCompact; });
  ipcMain.handle('ui:close', (e) => {
    const w = BrowserWindow.fromWebContents(e.sender);
    if (w && !w.isDestroyed()) w.close();
  });
  ipcMain.handle('ui:hideOverlay', () => {
    if (win.overlay) win.overlay.hide();
    closeWindow('mixer');
    maybeQuit();
  });
  ipcMain.handle('ui:quit', () => { app.quit(); });

  ipcMain.handle('shell:openFolder', () => shell.openPath(settings.get('outputDir')));
  ipcMain.handle('shell:reveal', (_e, file) => { if (file && fs.existsSync(file)) shell.showItemInFolder(file); });
  ipcMain.handle('shell:openExternal', (_e, url) => {
    if (/^https?:\/\//i.test(url)) shell.openExternal(url);
  });
  // ---- hotkey listener ----
  ipcMain.handle('listener:status', () => listenerStatus());
  ipcMain.handle('listener:setAutostart', (_e, on) => listenerRun(on ? '--install' : '--uninstall'));
  ipcMain.handle('listener:start', () => startListener());

  ipcMain.handle('shell:extensionPath', () => path.join(__dirname, '..', '..', 'extension'));
  ipcMain.handle('shell:openExtensionFolder', () => shell.openPath(path.join(__dirname, '..', '..', 'extension')));
}

// --------------------------------------------------------- hotkey listener

const LISTENER_EXE = path.join(__dirname, '..', '..', 'tools', 'LightRecorderHotkey.exe');

function listenerRun(flag) {
  return new Promise(resolve => {
    if (!fs.existsSync(LISTENER_EXE)) {
      return resolve({ ok: false, error: 'Listener is not built. Run: npm run listener:build' });
    }
    execFile(LISTENER_EXE, [flag], { windowsHide: true, timeout: 10000 }, (err, stdout, stderr) => {
      resolve(err
        ? { ok: false, error: (stderr || err.message || '').trim() }
        : { ok: true, output: String(stdout).trim() });
    });
  });
}

async function listenerStatus() {
  if (!fs.existsSync(LISTENER_EXE)) {
    return { built: false, running: false, autostart: false };
  }
  const r = await listenerRun('--status');
  const text = r.output || '';
  return {
    built: true,
    running: /listener\s*:\s*running/i.test(text),
    autostart: /autostart\s*:\s*on/i.test(text),
    raw: text
  };
}

/** Launch the listener detached so it outlives this process. */
function startListener() {
  return new Promise(resolve => {
    if (!fs.existsSync(LISTENER_EXE)) {
      return resolve({ ok: false, error: 'Listener is not built. Run: npm run listener:build' });
    }
    try {
      const child = spawn(LISTENER_EXE, [], { detached: true, stdio: 'ignore', windowsHide: true });
      child.unref();
      setTimeout(() => resolve({ ok: true }), 400);
    } catch (err) {
      resolve({ ok: false, error: err.message });
    }
  });
}

// ------------------------------------------------------------------- bridge

function wireBridge() {
  bridge = new Bridge(app.getPath('userData'));

  bridge.on('connected', info => { toast(`${info.browser} extension connected`, 'success'); pushState(); });
  bridge.on('disconnected', () => { pushState(); });
  bridge.on('tabs', () => pushState());
  bridge.on('error', msg => toast(`Bridge: ${msg}`, 'warn'));
  bridge.on('binary', chunk => tabRecorder.write(chunk));

  bridge.on('tabCaptureStarted', msg => {
    tabRecorder.setContainerFromMime(msg && msg.mime);
  });

  // The user pressed "Record this tab" in the extension popup. Chrome only
  // permits tab capture from a real click inside the extension, so this path
  // is browser-initiated and the app just opens the output file.
  bridge.on('tabRecordingStarting', msg => {
    if (isRecording()) return;
    const tab = bridge.tabs.find(t => t.id === msg.tabId);
    currentSource = {
      kind: 'tab',
      id: `tab:${msg.tabId}`,
      tabId: msg.tabId,
      name: tab ? tab.title : 'Browser tab'
    };
    activeMode = 'tab';
    try {
      tabRecorder.start({ settings: settings.all(), container: 'mp4' });
      if (tray) tray.setImage(trayImage(true));
    } catch (err) {
      activeMode = null;
      toast(`Could not start tab recording: ${err.message}`, 'error');
    }
    pushState();
  });

  bridge.on('tabCaptureError', msg => {
    toast(`Tab capture failed: ${msg}`, 'error');
    if (activeMode === 'tab') stopRecording();
  });
  bridge.on('tabCaptureStopped', () => {
    if (activeMode === 'tab' && tabRecorder.isRecording) stopRecording();
  });

  bridge.start(settings.get('bridgePort'));
}

// -------------------------------------------------------------------- recorder events

/**
 * Record what we asked ffmpeg to do and anything it complained about.
 * A failed encode otherwise leaves nothing but a zero-byte file, which is
 * impossible to diagnose after the fact.
 */
function writeLog(text) {
  try {
    fs.writeFileSync(path.join(app.getPath('userData'), 'last-recording.log'), text, 'utf8');
  } catch (_) { /* logging must never break recording */ }
}

function wireRecorderEvents() {
  const onProgress = p => broadcast('progress', p);
  recorder.on('progress', onProgress);
  tabRecorder.on('progress', onProgress);

  recorder.on('started', ({ file, args }) => {
    writeLog([
      `started : ${new Date().toISOString()}`,
      `output  : ${file}`,
      `ffmpeg  : ${encoderInfo.ffmpeg}`,
      `args    : ${args.map(a => (/\s/.test(a) ? `"${a}"` : a)).join(' ')}`,
      ''
    ].join('\n'));
  });

  recorder.on('stopped', result => {
    if (result && result.error) {
      try {
        const p = path.join(app.getPath('userData'), 'last-recording.log');
        fs.appendFileSync(p, `\nFAILED\n${result.error}\n`, 'utf8');
      } catch (_) {}
    }
  });

  recorder.on('error', msg => toast(msg, 'error'));
  tabRecorder.on('error', msg => toast(msg, 'error'));

  // ffmpeg dying on its own (disk full, encoder lost) must not leave the UI
  // stuck showing "recording".
  recorder.on('stopped', () => {
    if (activeMode === 'native' && recorder.state === 'idle') {
      destroyAudioWindow();
      activeMode = null;
      if (tray) tray.setImage(trayImage(false));
      pushState();
    }
  });
}

// ---------------------------------------------------------------------- tray

function createTray() {
  try {
    tray = new Tray(trayImage(false));
  } catch (_) {
    return;                       // tray is a convenience, not a requirement
  }
  const menu = Menu.buildFromTemplate([
    { label: 'Show recorder', click: () => { createOverlay().showInactive(); } },
    { label: 'Choose source…', click: () => { createOverlay().showInactive(); openPicker(); } },
    { type: 'separator' },
    { label: 'Start recording', click: () => startRecording() },
    { label: 'Stop recording', click: () => stopRecording() },
    { type: 'separator' },
    { label: 'Open save folder', click: () => shell.openPath(settings.get('outputDir')) },
    { label: 'Settings…', click: () => openSettings() },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ]);
  tray.setToolTip('Light Recorder');
  tray.setContextMenu(menu);
  tray.on('click', () => toggleOverlay());
}

// ---------------------------------------------------------------------- boot

/** Pull `--cmd=<name>` out of an argv, which is how the listener starts us. */
function commandFromArgv(argv) {
  const arg = (argv || []).find(a => typeof a === 'string' && a.startsWith('--cmd='));
  return arg ? arg.slice('--cmd='.length).trim() : null;
}

let commandServer = null;

if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  // A second launch means the listener could not reach our pipe (we were
  // still starting up). Honour the command instead of just showing the UI.
  app.on('second-instance', (_e, argv) => {
    cancelExit();
    const cmd = commandFromArgv(argv);
    if (cmd) runCommand(cmd);
    else createOverlay().showInactive();
  });

  app.whenReady().then(async () => {
    settings.init();

    // Auto-answer getDisplayMedia in our hidden audio window: we only want the
    // loopback audio track, so grant the first screen and take 'loopback'.
    session.defaultSession.setDisplayMediaRequestHandler(async (request, callback) => {
      try {
        const list = await desktopCapturer.getSources({ types: ['screen'], thumbnailSize: { width: 0, height: 0 } });
        callback({ video: list[0], audio: 'loopback' });
      } catch (_) {
        callback({});
      }
    }, { useSystemPicker: false });

    session.defaultSession.setPermissionRequestHandler((_wc, permission, cb) => {
      cb(permission === 'media' || permission === 'audioCapture');
    });

    currentSource = sources.defaultSource();

    wireIpc();
    wireRecorderEvents();
    wireBridge();
    createTray();
    createOverlay();

    commandServer = startCommandServer();
    writeListenerConfig();

    encoderInfo = await encoders.detect(settings.get('ffmpegPath'));
    if (!encoderInfo.ffmpeg) {
      toast('ffmpeg was not found - set its path in Settings before recording.', 'warn');
    }
    pushState();

    // If the listener started us to do something specific, do it now that
    // encoder detection has finished.
    const cmd = commandFromArgv(process.argv);
    if (cmd && cmd !== 'launch' && cmd !== 'toggleOverlay') runCommand(cmd);
  });

  // Closing the last window must not quit on its own; maybeQuit() decides,
  // so that a recording in progress is never cut short.
  app.on('window-all-closed', () => { maybeQuit(); });

  app.on('will-quit', () => {
    cancelExit();
    try { if (commandServer) commandServer.close(); } catch (_) {}
  });

  app.on('before-quit', async e => {
    if (isRecording()) {
      e.preventDefault();
      await stopRecording();
      app.exit(0);
      return;
    }
    try { await audioSessions.restoreAll(); } catch (_) {}
    audioSessions.shutdown();
    if (bridge) { bridge.restoreTabMutes(); bridge.stop(); }
  });
}
